- hosts: localhost
  become: true
  tasks:
    - dnf:
        name: "httpd"
        state: present
    - copy:
        src: "index.html"
        dest: "/var/www/html"
    - copy:
        src: "lw.conf"
        dest: "/etc/httpd/conf.d/lw.conf"
    - service:
        name: "httpd"
        state: restarted
        enabled: true
